cada/models.py
# -*- coding: utf-8 -*-
from flask_mongoengine import MongoEngine

db = MongoEngine()

PARTS = {
    1: {'label': "Avec audition de l'administration", 'help': "L'administration s'est déplacée à la séance"},
    2: {'label': 'Affaire de principe', 'help': "Etude et avis sur de nouveaux cas"},
    3: {'label': 'Affaire courante', 'help': "Avis sur des cas récurrents"},
    # TODO: ask CADA for proper wording
    4: {'label': 'Délégué', 'help': 'Avis rendu par délégation'},
}


class Advice(db.Document):
    id = db.StringField(primary_key=True)
    administration = db.StringField()
    type = db.StringField()
    session = db.DateTimeField()
    subject = db.StringField()
    topics = db.ListField(db.StringField())
    tags = db.ListField(db.StringField())
    meanings = db.ListField(db.StringField())
    part = db.IntField()
    content = db.StringField()

    def __unicode__(self):
        return self.subject

cada/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

from os.path import exists, join


class DefaultConfig(object):
    MONGODB_HOST = 'localhost'
    MONGODB_DB = 'cada'
    SECRET_KEY = 'no-secret-this-is-open'
    MAIL_DEFAULT_SENDER = 'cada@locahost'
    ANON_ALERT_MAIL = 'cada.alert@locahost'


def create_app(config=None):
    from flask import Flask

    from cada import views, api
    from cada.assets import assets
    from cada.models import db
    from cada.search import es

    app = Flask('cada')

    app.config.from_object(DefaultConfig)
    app.config.from_envvar('CADA_CONFIG', silent=True)

    custom_settings = join(os.getcwd(), 'cada.cfg')
    if exists(custom_settings):
        app.config.from_pyfile(custom_settings)

    if config:
        app.config.from_object(config)

    # Optionnal Sentry support
    if 'SENTRY_DSN' in app.config:
        from raven.contrib.flask import Sentry
        Sentry(app)

    db.init_app(app)
    es.init_app(app)
    assets.init_app(app)
    views.init_app(app)
    api.init_app(app)

    return app


if __name__ == '__main__':
    app = create_app()
    app.run()

cada/views.py
# -*- coding: utf-8 -*-
import io
import re

from datetime import datetime

from urllib.parse import urlsplit, urlunsplit

from flask import Blueprint, abort, render_template, url_for, request, flash, Response, redirect, current_app
from flask_mail import Attachment, Mail
from flask_wtf import FlaskForm
from jinja2 import Markup
from werkzeug import url_decode, url_encode
from wtforms import TextField, ValidationError
from wtforms.validators import InputRequired

from cada import csv
from cada.models import Advice, PARTS
from cada.search import search_advices, home_data

DEFAULT_PAGE_SIZE = 20

RE_URL = re.compile(r'https?://')


site = Blueprint('site', __name__)
mail = Mail()


@site.app_template_global(name='static')
def static_global(filename):
    return url_for('static', filename=filename)


@site.app_template_global()
@site.app_template_filter()
def url_rewrite(url=None, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(url or request.url)
    params = url_decode(query)
    for key, value in kwargs.items():
        params.setlist(key, value if isinstance(value, (list, tuple)) else [value])
    return Markup(urlunsplit((scheme, netloc, path, url_encode(params), fragments)))


@site.app_template_global()
@site.app_template_filter()
def url_add(url=None, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(url or request.url)
    params = url_decode(query)
    for key, value in kwargs.items():
        if value not in params.getlist(key):
            params.add(key, value)
    return Markup(urlunsplit((scheme, netloc, path, url_encode(params), fragments)))


@site.app_template_global()
@site.app_template_filter()
def url_del(url=None, *args, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(url or request.url)
    params = url_decode(query)
    for key in args:
        params.poplist(key)
    for key, value in kwargs.items():
        lst = params.poplist(key)
        if value in lst:
            lst.remove(value)
        params.setlist(key, lst)
    return Markup(urlunsplit((scheme, netloc, path, url_encode(params), fragments)))


@site.app_template_global()
def in_url(*args, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(request.url)
    params = url_decode(query)
    return (
        all(arg in params for arg in args)
        and
        all(key in params and params[key] == value for key, value in kwargs.items())
    )


@site.app_template_global()
@site.app_template_filter()
def treeize(topics, sep='/'):
    tree = {}
    for topic in topics:
        parts = topic.split(sep)
        if len(parts) == 1:
            tree[topic] = tree.get(topic, [])
        elif len(parts) == 2:
            if not parts[0] in tree:
                tree[parts[0]] = []
            tree[parts[0]].append(parts[1])
    return [(k, v) for k, v in sorted(tree.items())]


@site.app_template_global()
@site.app_template_filter()
def treeize_facet(topics, sep='/'):
    tree = {}
    for topic, count, active in topics:
        parts = topic.split(sep)
        if len(parts) == 1:
            tree[topic] = {
                'count': count,
                'active': active,
                'subtopics': tree.get(topic, {}).get('subtopics', [])
            }
        elif len(parts) == 2:
            if not parts[0] in tree:
                tree[parts[0]] = {
                    'count': count,
                    'active': active,
                    'subtopics': []
                }
            tree[parts[0]]['subtopics'].append((parts[1], count, active))
    return [
        (t, tree[t]['count'], tree[t]['active'], tree[t]['subtopics'])
        for t in sorted(tree, key=lambda k: tree[k]['count'])
    ]


@site.app_template_global()
@site.app_template_filter()
def part_label(part):
    return PARTS[int(part)]['label']


@site.app_template_global()
@site.app_template_filter()
def part_help(part):
    return PARTS[int(part)]['help']


@site.app_template_global()
def es_date(value):
    return datetime.strptime(value, '%Y-%m-%d').strftime('%d/%m/%Y')


@site.route('/')
def home():
    return render_template('index.html', **home_data())


@site.route('/search')
def search():
    return render_template('search.html', **search_advices())


@site.route('/about')
def about():
    return render_template('about.html')


class AlertAnonForm(FlaskForm):
    details = TextField(validators=[InputRequired()])

    def validate_details(form, field):
        if RE_URL.search(field.data):
            raise ValidationError("Vous ne pouvez pas soumettre d'URL")


@site.route('/<id>/')
def display(id):
    advice = Advice.objects.get_or_404(id=id)
    return render_template('advice.html', advice=advice, form=AlertAnonForm())


@site.route('/<id>/alert', methods=['POST'])
def alert(id):
    advice = Advice.objects.get_or_404(id=id)
    form = AlertAnonForm()
    if form.validate_on_submit():
        csvfile = io.StringIO()
        writer = csv.writer(csvfile)
        writer.writerow(csv.ANON_HEADER)
        writer.writerow(csv.to_anon_row(advice))
        attachment = Attachment(
            'cada-fix-{0}.csv'.format(advice.id),
            'text/csv',
            csvfile.getvalue()
        )
        mail.send_message("Défaut d'anonymisation sur l'avis CADA {0}".format(advice.id),
                          recipients=[current_app.config['ANON_ALERT_MAIL']],
                          html=render_template('anon_alert_mail.html', advice=advice, details=form.details.data),
                          attachments=[attachment]
                          )
        flash(
            "<strong>Merci pour votre contribution!</strong> Nous avons bien pris en compte votre signalement.",
            'success'
        )
        return redirect(url_for('site.display', id=advice.id))
    else:
        abort(400)


@site.route('/robots.txt')
def robots():
    return Response(render_template('robots.txt'), mimetype='text/plain')


@site.route('/sitemap.xml')
def sitemap():
    xml = render_template('sitemap.xml', advices=Advice.objects)
    return Response(xml, mimetype='application/xml')


@site.route('/export')
def export_csv():
    def generate():
        csvfile = io.StringIO()
        writer = csv.writer(csvfile)
        # Generate header
        writer.writerow(csv.HEADER)
        yield csvfile.getvalue()

        for advice in Advice.objects.order_by('id'):
            csvfile = io.StringIO()
            writer = csv.writer(csvfile)
            writer.writerow(csv.to_row(advice))
            yield csvfile.getvalue()

    date = datetime.now().date().isoformat()
    headers = {
        'Content-Disposition': 'attachment; filename=cada-{0}.csv'.format(date)
    }
    response = Response(generate(), mimetype="text/csv", headers=headers)
    return response


@site.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


def init_app(app):
    mail.init_app(app)
    app.register_blueprint(site)

cada/templates/about.html
{% extends "base.html" %}

{% block title %}À propos{% endblock %}

{% block content %}
<div class="row"><div class="col-md-9">
 
<h1 id="A-propos">À propos</h1>

<h2><a id="Etalab_0"></a>Etalab</h2>
<p>La mission <a href="https://etalab.gouv.fr">Etalab</a> fait partie de la Direction interministérielle du numérique et du système d’information et de communication de l’Etat (DINSIC), dont les missions sont fixées par les décrets du 20 novembre 2017.</p>
<p>Etalab est <a href="https://www.etalab.gouv.fr/qui-sommes-nous">notamment en charge</a> de coordonner la <strong>politique nationale d’ouverture et de partage des données publiques, ou <em>open data</em></strong>.</p>
<p>À ce titre, Etalab a développé le site <a href="http://cada.data.gouv.fr">cada.data.gouv.fr</a> en lien avec la <a href="https://cada.fr">CADA</a> afin de permettre la consultation en ligne des avis et des conseils émis depuis 1984. L’ensemble des données provient du jeu de données : <a href="http://www.data.gouv.fr/dataset/avis-et-conseils-de-la-cada">Avis et conseils de la CADA</a>, publié sur le site <a href="http://www.data.gouv.fr/">data.gouv.fr</a>.</p>
<h2><a id="Le_cadre_lgal_8"></a>Le cadre légal</h2>
<p>La politique d’open data, dont le cadre légal a été profondémment renouvelé par les lois <a href="https://www.legifrance.gouv.fr/eli/loi/2015/12/28/PRMX1515110L/jo/texte">Gratuité et modalités de réutilisation des informations publiques</a> et <a href="https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=70F06FAFE42AB53A449EF2AE222183BF.tplgfr23s_1?cidTexte=JORFTEXT000033202746&amp;categorieLien=id">République numérique</a> désormais codifiées dans le <a href="https://www.legifrance.gouv.fr/affichCode.do?cidTexte=LEGITEXT000031366350&amp;dateTexte=vig">Code des relations entre le public et d’administration</a>, puise en partie ses fondements dans le droit d’accès aux documents administratifs, institué par <a href="https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000000339241">loi CADA en 1978</a>.</p>
<p>La loi CADA permet aux particuliers de demander des documents à l’ensemble des administrations centrales et locales. Ces dernières ont l’obligation d’y répondre, favorablement ou défavorablement.</p>
<h2><a id="La_CADA_15"></a>La CADA</h2>
<p>La Commission d’accès aux documents administratifs est une autorité administrative indépendante chargée de veiller à la liberté d’accès aux documents administratifs et aux archives publiques ainsi qu’à la réutilisation des informations publiques.</p>
<p>Elle peut être saisie par les personnes (physiques ou morales) qui se sont vues opposer une décision défavorable en matière d’accès ou de publication de documents administratifs ou de réutilisation d’informations publiques. La commission peut aussi être saisie, à titre de conseil, par les administrations sollicitées en ces matières.</p>
<p>Le recours devant la CADA constitue un préalable obligatoire à tout recours contentieux (article L. 342-1 du CRPA).</p>
<p>Avant la saisine de la commission, une demande d’accès ou de publication de documents administratifs ou de réutilisation d’informations publiques doit être adressée à l’administration qui détient le document. En cas de refus, la saisine de la CADA est possible. Afin de faciliter les démanches des particuliers, la commission propose un <a href="https://www.cada.fr/formulaire-de-saisine">formulaire de saisine en ligne</a>.</p>
<p>Le site <a href="http://cada.data.gouv.fr">cada.data.gouv.fr</a> permet notamment de rechercher dans la doctrine de la CADA si cette dernière a déjà remis un avis sur un document.</p>
<h2><a id="Liens_utiles_28"></a>Liens utiles</h2>
<ul>
    <li><a href="https://www.cada.fr/particulier/quand-et-comment-saisir-la-cada">Quand et comment saisir la CADA ?</a></li>
    <li><a href="https://www.cada.fr/administration/modalites-de-communication">Modalités de communication des documents</a></li>
    <li><a href="https://www.cada.fr/administration/les-fiches-thematiques">Fiches thématiques relatives aux documents fréquemment demandés</a> (environnement, marchés publics, gestion des collectivités territoriales…)</li>
</ul>

</div></div>
{% endblock %}

cada/templates/advice.html
{% extends "base.html" %}

{% block title %}{{ advice.type.title() }} {{ advice.id }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <h1>
            {{ advice.type.title() }} {{ advice.id }}
            <small>Séance du {{ advice.session.strftime('%d/%m/%Y') }}</small>
        </h1>
        <div class="lead subject raw">
            {{- advice.subject -}}
        </div>
        <div class="content raw">
            {{ advice.content }}
        </div>
    </div>
    <aside class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-home"></span>
                Administration
            </div>
            <div class="panel-body">
                <a href="{{ url_for('site.search', administration=advice.administration) }}">
                    {{ advice.administration }}
                </a>
            </div>

            <div class="panel-heading">
                <span class="glyphicon glyphicon-bullhorn"></span>
                Type de consultation
            </div>
            <div class="panel-body">
                {% if advice.part  %}
                <a href="{{ url_for('site.search', part=advice.part) }}"
                    data-toggle="popover" title="{{advice.part|part_label}}"
                    data-content="{{advice.part|part_help}}" data-trigger="hover">
                    {{ advice.part|part_label }}
                </a>
                {% endif %}
            </div>

            <div class="panel-heading">
                <span class="glyphicon glyphicon-book"></span>
                Thèmes
            </div>
            <div class="panel-body topics">
                {% for topic, subtopics in advice.topics|treeize %}
                    <a href="{{url_for('site.search', topic=topic) }}"
                        class="label label-primary topic">
                        <span class="glyphicon glyphicon-folder-{{'open' if subtopics else 'close'}}"></span>
                        {{ topic }}
                    </a>
                    {% for subtopic in subtopics %}
                    <a class="label label-default subtopic"
                        href="{{ url_for('site.search', topic=topic+'/'+subtopic) }}">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        {{ subtopic }}
                    </a>
                    {% endfor %}
                {% endfor %}
            </div>

            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                Conclusions
            </div>
            <div class="panel-body">
                {% for meaning in advice.meanings %}
                <a
                	{% if "défavorable" in meaning.lower() %}
                    class="label label-danger"
                    {% elif "favorable" in meaning.lower() %}
                    class="label label-success"
                    {% else %}
                    class="label label-warning"
                    {% endif %}
                    href="{{url_for('site.search', meaning=meaning) }}">{{ meaning }}</a>
                {% endfor %}
            </div>

            <div class="panel-heading">
                <span class="glyphicon glyphicon-tags"></span>
                Mots-clés
            </div>
            <div class="panel-body">
                {% for tag in advice.tags %}
                <a href="{{url_for('site.search', tag=tag) }}" class="label label-primary">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>

        <div class="issue">
            <a
                class="btn btn-xs btn-info btn-block"
                title="Signaler un défaut d'anonymisation"
                href="https://support.data.gouv.fr">
                Signaler un défaut d'anonymisation
            </a>
        </div>
    </aside>
</div>
{% endblock %}

cada/templates/anon_alert_mail.html
<p>
Un défaut d'anonymisation a été signalé sur
l'<a href="{{ url_for('site.display', id=advice.id, _external=True) }}">avis CADA {{advice.id}}</a>.
</p>

{% if details %}
<p><b>Informations complémentaires fournies par le lanceur d'alerte:</b></p>
<p><i>{{details}}</i></p>

<p>L'avis en question est en pièce jointe au format CSV.</p>
{% endif %}

cada/templates/base.html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="data:," />

    <title>{% block title %}Sans titre{% endblock %} - CADA</title>

    {% assets "css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
</head>
<body>
    <main class="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        <a href="/">CADA</a>
                        <small>
                        par
                        <a href="http://www.data.gouv.fr">data.gouv.fr</a>
                        </small>
                    </div>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ url_for('site.about') }}">À propos</a></li>
                        <li><a href="{{ url_for('api.doc') }}">Documentation de l'API</a></li>
                    </ul>
                    {# Optionnal search bar #}
                    {% set display_search = display_search|default(True) %}
                    {% if display_search %}
                    <form class="navbar-form navbar-right" role="search"
                        action="{{ url_for('site.search') }}">
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Recherche"
                                    name="q" value="{{ request.args.q }}">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </form>
                    {% endif %}
                </div>
            </div>
        </nav>


        <div class="container">
            {% for  category, message in get_flashed_messages(with_categories=true) %}
            <div class="alert alert-{{category|default('info')}} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message|safe }}
            </div>
            {% endfor %}

            <div class="page">
            {% block content %}{% endblock %}
            </div>
        </div>

        {% include "footer.html" %}
    </main>

    {% assets "js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% block extra_js %}{% endblock %}

    {% include "piwik.html" %}
</body>
</html>

cada/templates/footer.html
<section class="footer">
    <div class="container">
        <footer class="row">

            <section class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <h5>Ce site</h5>
                <p>Ce site est une réutilisation du <a href="https://www.data.gouv.fr/dataset/avis-et-conseils-de-la-cada">jeu de données Avis et conseil de la CADA</a> publié sur le site <a href="http://www.data.gouv.fr/">data.gouv.fr</a>.</p>
                <p>Il permet de rechercher et explorer simplement les avis et conseils émis par la CADA depuis 1984.</p>
            </section>

            <section class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                <h5>Réseau</h5>
                <ul>
                    <li><a href="https://www.info.gouv.fr/">info.gouv.fr</a></li>
                    <li><a href="https://www.france.fr/">France.fr</a></li>
                    <li><a href="https://www.legifrance.gouv.fr/">Legifrance.gouv.fr </a></li>
                    <li><a href="https://www.service-public.fr/">Service-public.fr</a></li>
                    <li><a href="http://opendatafrance.net/">Opendata France</a></li>
                    <li><a href="https://www.cada.fr/">CADA.fr</a></li>
                </ul>
            </section>

            <section class="col-xs-6 col-sm-3 col-md-4 col-lg-4">
                <h5>Contact</h5>
                <ul>
                    <li><a href="https://twitter.com/Etalab">Twitter</a></li>
                    <li><a href="https://github.com/etalab">GitHub</a></li>
                    <li><a href="https://support.data.gouv.fr/">Support</a></li>
                </ul>
            </section>

            <section class="col-xs-9 col-xs-offset-3 col-sm-offset-0 col-sm-2 col-md-2 col-lg-2">
                <a href="https://www.etalab.gouv.fr/">
                <img class="logo" src="{{ static('img/etalab.svg') }}" />
                </a>
            </section>

            <p class="bottom-right"><a href="#">Haut de page</a></p>

        </footer>
    </div>
</section>

cada/templates/index.html
{% extends "base.html" %}
{% set display_search = False %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="container-full">
    <div class="row">
        <div class="col-sm-12 text-center v-center">
            <form class="col-sm-12 megasearch" action="{{ url_for('site.search') }}">
                <div class="input-group">
                    <input name="q" class="form-control input-lg"
                        placeholder="Retrouvez un avis CADA parmi les {{total}} disponibles {% if total %}({{sessions.from.strftime('%d/%m/%Y')}} au {{sessions.to.strftime('%d/%m/%Y')}}){% endif %}"
                        type="text">
                    <div class="input-group-btn">
                        <button class="btn btn-lg btn-primary" type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h3>Mots-clés</h3>
            <ul class="tags blue">
                {% for tag, count in tag_cloud %}
                    <li>
                        <a href="{{ url_for('site.search', tag=tag) }}">
                            {{ tag }}
                            <span>{{ count }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-6">
            <h3>Thèmes</h3>
            <ul class="tags topics">
                {% for topic, count in topics %}
                    <li>
                        <a href="{{ url_for('site.search', topic=topic) }}">
                            {{ topic }}
                            <span>{{ count }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

cada/templates/search.html
{% extends "base.html" %}
{% import 'macros.html' as m %}
{% set display_search = False %}

{% set sorters = {
    'topic': ('Thème', 'alphabet'),
    'administration': ('Administration', 'alphabet'),
    'session': ('Séance', 'order'),
} %}

{% block title %}Recherche{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8">

        <div class="row">
            <form class="col-lg-12" action="{{ url_for('site.search', **request.args) }}">
                <div class="input-group">
                    <input type="text" name="q" class="form-control"
                        placeholder="Recherche" value="{{ request.args.q }}">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            {% if in_url('sort') %}
                                {% set sort, order = request.args.sort.split(' ') %}
                                {% set label, type = sorters[sort] %}
                                {% set suffix = '-alt' if order == 'desc' else '' %}
                                <span class="glyphicon glyphicon-sort-by-{{type}}{{suffix}}"></span>
                                {{ label }}
                            {% else %}
                                <span class="glyphicon glyphicon-sort-by-attributes-alt"></span>
                                Pertinence
                            {% endif %}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="{{ url_rewrite(page=1)|url_del('sort') }}">
                                    Pertinence
                                </a>
                            </li>
                            {% for field, (label, type) in sorters.items() %}
                                {{ m.sorter_entries(field, label, type) }}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="col-sm-12 label-list">
                {{ m.filter_label('administration', 'Administration', 'home') }}
                {{ m.filter_label('session', 'Séance', 'calendar', es_date) }}
                {{ m.filter_label('tag', 'Mot-clé', 'tag') }}
                {{ m.filter_label('topic', 'Thème', 'book') }}
                {{ m.filter_label('part', 'Mode de consultation', 'bullhorn', part_label) }}
                {{ m.filter_label('meaning', 'Conclusion', 'comment') }}
            </div>
        </div>

        <hr/>

        <ul class="list-unstyled search-result">
            {% for advice in advices %}
            <li>
                <a class="title" href="{{ url_for('site.display', id=advice.id) }}">
                    {{ advice.type.title() }} {{ advice.id }}
                </a>
                <div class="subtitle">
                    <span class="glyphicon glyphicon-home"></span>
                    {{ advice.administration }}
                </div>
                <div class="excerpt">{{ advice.subject|truncate(100) }}</div>
                <div class="label-list">
                    <a class="label label-info" title="Séance"
                        href="{{url_for('site.search', session=advice.session.strftime('%Y-%m-%d')) }}">
                        <span class="glyphicon glyphicon-calendar"></span>
                        {{ advice.session.strftime('%d/%m/%Y') }}
                    </a>
                    {% for meaning in advice.meanings %}
                    <a
                        {% if "défavorable" in meaning.lower() %}
                        class="label label-danger"
                        {% elif "favorable" in meaning.lower() %}
                        class="label label-success"
                        {% else %}
                        class="label label-warning"
                        {% endif %}
                        title="Conclusion"
                        href="{{url_for('site.search', meaning=meaning) }}">
                        <span class="glyphicon glyphicon-comment"></span>
                        {{ meaning }}
                    </a>
                    {% endfor %}
                    {% for topic in advice.topics %}
                    <a class="label label-primary" title="Thème"
                        href="{{url_for('site.search', topic=topic) }}">
                        <span class="glyphicon glyphicon-book"></span>
                        {{ topic }}
                    </a>
                    {% endfor %}
                    {% for tag in advice.tags %}
                    <a class="label label-default" title="Tag"
                        href="{{url_for('site.search', tag=tag) }}">
                        <span class="glyphicon glyphicon-tag"></span>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </div>
            </li>
            {% else %}
            <li>Aucun résultat</li>
            {% endfor %}
        </ul>

        {{ m.paginator(page, page_size, total) }}

    </div>
    <aside class="col-md-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                {% if total %}
                    Résultats {{ ((page - 1) * page_size) + 1 }}
                    à {{ page * page_size if page * page_size <= total else total }}
                    sur {{ total }} trouvés.
                {% else %}
                    Aucun résultat trouvé
                {% endif %}
            </div>
            {{ m.facet_filter(facets, 'administration', 'Administrations', 'home') }}
            {{ m.facet_filter(facets, 'session', 'Séances', 'calendar', es_date) }}
            {{ m.facet_filter(facets, 'tag', 'Mots-clés', 'tags') }}
            {{ m.tree_facet_filter(facets, 'topic', 'Thèmes', 'book') }}
            {{ m.facet_filter(facets, 'meaning', 'Conclusions', 'comment') }}
            {{ m.facet_filter(facets, 'part', 'Modes de consultation', 'bullhorn', part_label) }}
        </div>

    </aside>
</div>

{% endblock %}